# Generated by Django 4.2.6 on 2023-10-09 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('manzil', models.CharField(max_length=150)),
                ('ism', models.CharField(max_length=150)),
                ('tel', models.CharField(max_length=15)),
                ('qarz', models.PositiveBigIntegerField()),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('narx', models.PositiveBigIntegerField()),
                ('miqdor', models.CharField(max_length=50)),
                ('olchov', models.CharField(max_length=10)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
